# 🧪 Pandas Wrangle Lab: Clean & Explore a Real Dataset

## 🔹 LEARNING GOALS:
- Practice loading, cleaning, and exploring real-world data
- Apply column creation, renaming, sorting, and filtering
- Use `.info()`, `.describe()`, and `.query()` fluently

### 📥 1. Load the Dataset

In [16]:
import pandas as pd
df = pd.read_csv(r"c:\Users\Victoria Heredia\Downloads\4543_SpatialData\Assignments\01-Python_Foundations\04-Foundations\Lessons\04-Data_Input_Output\students.csv")
df.head()

      Name  Age  Score
0    Alice   23     90
1      Bob   25     85
2  Charlie   22     95
3    David   24     64
4      Eve   21     67

### 🔎 2. Inspect and Audit the Data

In [20]:
# Basic overview
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        3 non-null      str
 1   age         3 non-null      int64
 2   score       3 non-null      int64
 3   grade       3 non-null      str
 4   first_name  3 non-null      object
 5   last_name   3 non-null      object
dtypes: int64(2), object(2), str(2)
memory usage: 276.0+ bytes

In [19]:
# Summary stats
df.describe()

             age  score
count   3.000000    3.0
mean   23.333333   90.0
std     1.527525    5.0
min    22.000000   85.0
25%    22.500000   87.5
50%    23.000000   90.0
75%    24.000000   92.5
max    25.000000   95.0

### 🧼 3. Clean Missing or Invalid Data

In [18]:
# Check for missing values
df.isnull().sum()

name          0
age           0
score         0
grade         0
first_name    0
last_name     0
dtype: int64

In [14]:
# Drop rows with missing names
df.dropna(subset=["first_name", "last_name"], inplace=True)

# Fill any missing scores with column average
df["score"].fillna(df["score"].mean(), inplace=True)

C:\Users\Victoria Heredia\AppData\Local\Temp\ipykernel_29220\889405405.py:5: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df["score"].fillna(df["score"].mean(), inplace=True)

0    90
1    85
2    95
3    64
4    67
5    88
6    72
7    91
Name: score, dtype: int64

### 🧠 4. Feature Engineering (New Columns)

In [12]:
# Add average and grade
df["average_score"] = df["score"]

def grade(score):
    if score >= 90:
        return "A"
    elif score >= 80:
        return "B"
    elif score >= 70:
        return "C"
    else:
        return "D"

df["grade"] = df["average_score"].apply(grade)
df.head()

      name  age  score grade first_name last_name  average_score
0    Alice   23     90     A      Alice     Alice             90
1      Bob   25     85     B        Bob       Bob             85
2  Charlie   22     95     A    Charlie   Charlie             95
3    David   24     64     D      David     David             64
4      Eve   21     67     D        Eve       Eve             67

### 🔽 5. Sorting and Filtering

In [10]:
# Top performers
df[df["score"] > 90].sort_values(by="score", ascending=False).head()

      name  age  score grade first_name last_name
2  Charlie   22     95     A    Charlie   Charlie
7    Heidi   24     91     A      Heidi     Heidi

### 📊 6. Group and Describe by Grade

In [14]:
# How many of each grade?
df["grade"].value_counts()

grade
A    2
B    1
Name: count, dtype: int64

In [8]:
# Average scores per grade group
df.groupby("grade")["score"].mean()

grade
A    92.0
B    86.5
C    72.0
D    65.5
Name: score, dtype: float64

### 💾 7. Save the Cleaned Dataset

In [12]:
df.to_csv("student_scores_cleaned.csv", index=False)

### 🧠 Challenge Task

> Your turn! Filter out students who got a D, sort by last name, and export to a new file:
- Only include columns: `first_name`, `last_name`, `grade`
- Save it as `"d_students.csv"`

In [2]:
import pandas as pd

# Load dataset
df = pd.read_csv(r"c:\Users\Victoria Heredia\Downloads\4543_SpatialData\Assignments\01-Python_Foundations\04-Foundations\Lessons\04-Data_Input_Output\students.csv")

df.columns = df.columns.str.lower().str.replace(" ", "_")

def assign_grade(score):
    if score >= 90:
        return "A"
    elif score >= 80:
        return "B"
    elif score >= 70:
        return "C"
    elif score >= 60:
        return "D"
    else:
        return "F"

df["grade"] = df["score"].apply(assign_grade)

df["first_name"] = df["name"].str.split().str[0]
df["last_name"] = df["name"].str.split().str[-1]


d_students = df[df["grade"] == "D"]
d_students = d_students.sort_values(by="last_name")
d_students = d_students[["first_name", "last_name", "grade"]]

d_students.to_csv("d_students.csv", index=False)

print(d_students)

  first_name last_name grade
3      David     David     D
4        Eve       Eve     D

### 📝 Summary

This lab gave you hands-on experience with:
- Cleaning nulls and type mismatches
- Creating new columns
- Filtering and sorting real data
- Grouping and summarizing by categorical features

Your data wrangling toolbox is now ready for real-world messiness. 🧹🛠️