# 📊 04 - Data Input and Output

Most of data science is about **loading data, exploring it, and saving results**.  
In this notebook you will learn:
- Reading CSV files with Pandas
- Inspecting DataFrames (`head`, `info`, `describe`)
- Writing data back to CSV
- Reading Excel files (if available)

## 1. Reading CSV Files

In [2]:
import pandas as pd

# Create a small CSV for demo
data = """Name,Age,Score
Alice,23,90
Bob,25,85
Charlie,22,95
David,24,64
Eve,21,67
Frank,26,88
Grace,23,72
Heidi,24,91
"""
with open("students.csv", "w") as f:
    f.write(data)

# Read CSV into DataFrame
df = pd.read_csv("students.csv")
df

      Name  Age  Score
0    Alice   23     90
1      Bob   25     85
2  Charlie   22     95
3    David   24     64
4      Eve   21     67
5    Frank   26     88
6    Grace   23     72
7    Heidi   24     91

✅ **Your Turn**: Create your own small CSV (3–5 rows) and read it into Pandas.

In [ ]:
import csv
import pandas as pd

with open("my_data.csv", "w", newline="") as file:
    writer = csv.writer(file)

    writer.writerow(["Item", "Category", "Score"])

    writer.writerow(["Laptop", "Tech", 90])
    writer.writerow(["Book", "Study", 85])
    writer.writerow(["Headphones", "Tech", 88])
    writer.writerow(["Notebook", "Study", 92])

   

df = pd.read_csv("my_data.csv")
print(df)

         Item Category  Score
0      Laptop     Tech     90
1        Book    Study     85
2  Headphones     Tech     88
3    Notebook    Study     92

## 2. Exploring DataFrames

In [5]:
# Look at the first rows
df.head()

         Item Category  Score
0      Laptop     Tech     90
1        Book    Study     85
2  Headphones     Tech     88
3    Notebook    Study     92

In [6]:
# Info about columns and data types
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Item      4 non-null      str
 1   Category  4 non-null      str
 2   Score     4 non-null      int64
dtypes: int64(1), str(2)
memory usage: 228.0 bytes

In [7]:
# Summary statistics
df.describe()

           Score
count   4.000000
mean   88.750000
std     2.986079
min    85.000000
25%    87.250000
50%    89.000000
75%    90.500000
max    92.000000

✅ **Your Turn**: Use `.head()` to preview your dataset and `.describe()` to see basic statistics.

In [9]:
import pandas as pd

df = pd.read_csv("my_data.csv")

print(df.head())

print(df.describe())

         Item Category  Score
0      Laptop     Tech     90
1        Book    Study     85
2  Headphones     Tech     88
3    Notebook    Study     92
           Score
count   4.000000
mean   88.750000
std     2.986079
min    85.000000
25%    87.250000
50%    89.000000
75%    90.500000
max    92.000000

## 3. Writing CSV Files

In [ ]:
# Save the DataFrame to a new CSV
df.to_csv("students_copy.csv", index=False)
%ls *.csv

✅ **Your Turn**: Save your DataFrame to a CSV file called `my_data.csv`.

In [10]:
import pandas as pd

df = pd.DataFrame({
    "Item": ["Laptop", "Book", "Headphones"],
    "Category": ["Tech", "Study", "Tech"],
    "Score": [90, 85, 88]
})

df.to_csv("my_data.csv", index=False)

## 4. Reading Excel Files

In [ ]:
# Optional: Requires 'openpyxl' installed
# Save to Excel
df.to_excel("students.xlsx", index=False)

# Read Excel file
pd.read_excel("students.xlsx")

✅ **Your Turn**: Try saving your dataset to Excel and reading it back (if supported in your environment).

In [14]:
import pandas as pd

df = pd.DataFrame({
    "Item": ["Laptop", "Book", "Headphones"],
    "Category": ["Tech", "Study", "Tech"],
    "Score": [90, 85, 88]
})

df.to_excel("my_data.xlsx", index=False)
df_loaded = pd.read_excel("my_data.xlsx")
print(df_loaded)

         Item Category  Score
0      Laptop     Tech     90
1        Book    Study     85
2  Headphones     Tech     88

---
### Summary
- `pd.read_csv` loads data into a DataFrame.
- Use `.head()`, `.info()`, `.describe()` to explore quickly.
- `df.to_csv` and `df.to_excel` save results.
- Pandas makes file I/O simple and reliable.